In [14]:
# This script will be used to generate the NET matrix for the HCP_1200 subject release
# Note that for this release, the subject partial correlations were provided in a .txt file in a matrix of size subjects x 200^2
# "The individual subjects’ netmats are saved as raw text files, with one row per subject; each row
# contains the NxN matrix of connectivity estimates, unwrapped to a long single row of N^2 values. The row ordering matches the list of subject IDs
# saved in the file subjectIDs.txt"

# See docs here: https://www.humanconnectome.org/storage/app/media/documentation/s1200/HCP1200-DenseConnectome+PTN+Appendix-July2017.pdf

#!/usr/bin/python3

import numpy as np
import pandas as pd
from pandas import DataFrame
from numpy import genfromtxt
import os, sys
from pprint import pprint

cwd = os.getcwd()
inputs = os.path.abspath("__file__"+"/../../inputs")
outputs = os.path.abspath("__file__"+"/../../outputs") # NOTE CHANGE THIS TO YOUR DESIRED OUTPUT PATH!

netmat_fp = os.path.join(inputs, 'netmats2.txt') # name of the .txt provided by HCP database

netmat = pd.read_csv(netmat_fp, delim_whitespace=True, header=None)
print(netmat.shape)

(1003, 40000)


In [15]:
subject_ids_fp = os.path.join(inputs, 'subjectIDs.txt')
subjects = [line.rstrip('\n') for line in open(os.path.join(cwd,subject_ids_fp))]

In [19]:
# reindex the netmat matrix so it has the subject IDs as row labels
netmat.index = subjects

In [20]:
# Confirm that re-indexing worked
netmat

0       1        2        3       4        5        6        7      \
100206      0 -2.5723  0.39576  1.57390 -2.9039  0.36927   2.0793  2.27970   
100307      0 -2.8707  4.24250  4.87750 -5.8280  0.06896  11.2160 -1.15470   
100408      0 -2.5092  3.28550 -0.54879 -1.0605  0.43553  11.9850 -0.10458   
100610      0 -4.1998  4.24920  6.19830 -4.0945  0.48348   1.3559  2.90420   
101006      0 -2.4770  6.64910  3.13700 -5.1657 -0.27481   6.4439  5.87380   
...       ...     ...      ...      ...     ...      ...      ...      ...   
992673      0 -1.9631  2.74250  7.79610 -5.8029  0.93827  22.5330  0.84908   
992774      0 -3.6917  7.28150  2.86970 -1.3173  1.21200  16.6650  3.46350   
993675      0 -4.0004  1.82180  6.60910 -7.1598  1.06500   1.3884  0.25915   
994273      0 -1.9784 -1.73330 -0.30014 -1.8110 -0.23622   8.8542  3.70900   
996782      0  1.6474  0.23679  4.25810 -4.8025  0.29021   8.2228  5.90680   

           8         9      ...    39990     39991     39992    39993  \
100206 -1.212100  0.124000  ... -1.50270  0.836170 -0.075309  0.28334   
100307 -0.358680  2.228900  ... -1.60030  0.590580 -0.683540 -0.18341   
100408  1.584000  1.539600  ... -2.46350 -1.515000 -1.553900  0.85661   
100610 -0.446070  2.152600  ... -0.42396  0.441950  0.707120 -1.29370   
101006  0.000581  2.043800  ... -2.36930 -0.050175  0.952960 -1.47440   
...          ...       ...  ...      ...       ...       ...      ...   
992673 -0.296070  0.020349  ... -1.49560 -0.201780 -0.118690  0.54990   
992774  1.179100  2.398500  ... -0.65353 -0.805250 -3.335300  0.93078   
993675 -1.218200  1.551400  ... -0.28573  0.596040 -1.610700  0.57494   
994273  1.568000  0.969100  ... -1.06650  0.617480 -0.917110  0.81260   
996782 -1.071500  3.033100  ... -1.88510  0.079622  0.976250  0.25167   

          39994     39995    39996    39997    39998  39999  
100206 -2.68740 -0.017961  0.55964 -0.23654 -1.16040      0  
100307 -2.36780 -2.641400  1.86210  0.36602 -2.20700      0  
100408 -1.56980 -2.073400  0.24246 -0.25569 -4.88840      0  
100610 -2.93830 -3.110700  3.24290 -1.05190 -1.74640      0  
101006 -0.65658 -1.316400  0.67285 -0.39485 -0.31321      0  
...         ...       ...      ...      ...      ...    ...  
992673 -2.80400 -2.319900 -0.12447 -1.28990 -0.50561      0  
992774 -1.58710 -3.760700  2.26280 -1.69450 -1.53580      0  
993675 -0.57447 -2.960300  2.69900  1.10610 -2.09840      0  
994273 -1.33320 -2.315000  1.41220  0.56316 -1.18660      0  
996782 -1.68910 -1.758500  2.18740 -0.65288 -1.33110      0  

[1003 rows x 40000 columns]

In [88]:
myList = [] # list of the subject x 200*199/2 matrix enties (the lower diagonal)
col = 200

for index, row in netmat.iterrows():
    arr = row.to_numpy() # make into a numpy array
    mat = np.array([arr[i:i+col] for i in range(0, len(arr), col)]) 
    
    flat_lower_tri = mat[np.tril(mat, -1) !=0]
    myList.append(flat_lower_tri)

In [90]:
myList

[array([-2.5723 ,  0.39576, 12.61   , ...,  0.55964, -0.23654, -1.1604 ]),
 array([-2.8707 ,  4.2425 , 10.858  , ...,  1.8621 ,  0.36602, -2.207  ]),
 array([-2.5092 ,  3.2855 ,  5.5259 , ...,  0.24246, -0.25569, -4.8884 ]),
 array([-4.1998,  4.2492,  8.2713, ...,  3.2429, -1.0519, -1.7464]),
 array([-2.477  ,  6.6491 , 15.626  , ...,  0.67285, -0.39485, -0.31321]),
 array([-3.601 ,  5.5732,  8.5542, ...,  1.8323, -2.1585, -1.2028]),
 array([-4.4528 , 10.718  , 10.66   , ...,  0.33808, -0.24025, -1.4414 ]),
 array([-2.4193,  2.6372, 15.269 , ...,  2.0643, -2.6517, -1.4727]),
 array([-6.8445 ,  2.7577 , 12.763  , ...,  0.37968,  0.39231, -3.0588 ]),
 array([-2.7356,  3.0572, 12.215 , ...,  1.4768, -1.3315, -2.5025]),
 array([ 1.6391,  1.093 , 11.902 , ...,  2.1121,  1.139 , -4.1271]),
 array([-1.6927 ,  0.74775, 12.679  , ...,  1.5003 ,  0.8193 , -0.11243]),
 array([-2.3499 ,  5.4823 ,  8.1053 , ...,  1.3492 , -1.3564 , -0.29685]),
 array([-5.1765 ,  4.156  , 10.875  , ...,  0.39674,  0

In [92]:
output_fp = os.path.join(outputs, 'NET.txt')
matrix = np.array(myList)
print("Resulting matrix shape:" ,matrix.shape)
np.savetxt(fname=output_fp, X=matrix, delimiter=',')

Resulting matrix shape: (1003, 19900)
